#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-3
LC_ALL=C
SECONDS=0
fecha=$(date +%d-%m-%Y)
cssh="ssh -4 -C -q -o StrictHostKeyChecking=no -o ConnectTimeout=3 -p 22"
cuser="username"
correo='swaks -4 --to mail1@test.com,mail2@test.com --from user@test.com --server mail.test.com:587 -tls --auth LOGIN --auth-user user@test.com --auth-password PASSWORD'
ips=(x.x.x.x y.y.y.y z.z.z.z)
archi="/home/user/claves.txt"
donde="/home/user"
ctar="tar -czf"
qre="qrencode -c -m 1 -s 10 -l H -d 100"

function clean_1() {
	rm -f $archi
	rm -f $donde/*.tar.gz
	rm -rf $donde/qr/
}

if [[ "$EUID" = "0" ]]; then
	echo -e "\e[00;31mERROR: NO debe ser root.\e[00m"
	exit 1
fi

trap "clean_1; exit" 0 1 2 3 9 15
clear

mkdir -p $donde/qr

for i in ${ips[@]}; do
	clave=$(dd if=/dev/urandom bs=1 count=64 2>/dev/null | base64 -w 0 | tr -dc _A-Z-a-z-0-9 | cut -c 1-8)
	echo "IP: $i"
	echo "IP: $i" >> $archi
	echo "Clave: $clave"
	echo "Clave: $clave" >> $archi
	echo "=========================" >> $archi
	$qre "WIFI:T:WPA;S:REALSSID;P:$clave;;" -o $donde/qr/$i.png
	$cssh $cuser@$i "caps-man security set visita passphrase=$clave"
done

#comprimir
$ctar $donde/qr-$fecha.tar.gz $donde/qr/

#correo
echo "correo"
$correo --output $donde/clavewifi.log --header "Subject: Cambio de clave de SSID REALSSID %DATE%" --body "Se cambiaron las claves de los SSID REALSSID, se adjunta el archivo." --attach $archi --attach $donde/qr-$fecha.tar.gz
echo "duracion $SECONDS segundos"
echo "Finalizado."
exit 0
